language: java
jdk:
  - openjdk11

branches:
  only:
    - travis

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - hjwoou@gmail.com